### ISSUE TITLE
Document the command line options

### ISSUE THREAD

**Issue by clandrew** [Trinity-11/FoenixIDE#29]
They are hard to discover right now. Also apparently /h and /? and --help don't output help with usage

**Comment by clandrew** [comment]
because the usage message is printed with Console.Out.WriteLine, but output is blocked by Windows Forms

**Comment by dtremblay** [comment]
**In release 0.6.0.9:**
I will add -h and /? to display the help.  This means that now, -k and --kernel will be used to load a kernel from the command prompt.  The --kernel option accepts any valid .pgz, .pgx, .hex and .bin files instead of only .hex.  
The --board option now accepts b, c, u, u+, jr and jr816.
